<?php
$stock=new array ();
$stock[] = new array ('name'=>'Abacus','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Abacus','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'2 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Acid (vial)','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage, Utility');
$stock[] = new array ('name'=>'Acid (vial)','type'=>,'Adventuring Gear','cost'=>,'25 gp','weight'=>,'1 lb','notes'=>,'Combat, Damage, Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Fire (flask)','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Consumable, Damage, Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Fire (flask)','type'=>,'Adventuring Gear','cost'=>,'50 gp','weight'=>,'1 lb','notes'=>,'Combat, Consumable, Damage, Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Supplies','type'=>'Tool','cost'=>'50 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Supplies','type'=>,'Tool','cost'=>,'50 gp','weight'=>,'8 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Amulet','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Amulet','type'=>,'Holy Symbol','cost'=>,'5 gp','weight'=>,'1 lb','notes'=>,'Utility');
$stock[] = new array ('name'=>'Antitoxin','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Healing, Utility');
$stock[] = new array ('name'=>'Antitoxin','type'=>,'Adventuring Gear','cost'=>,'50 gp','weight'=>,'--','notes'=>,'Healing, Utility');
$stock[] = new array ('name'=>'Arrows','type'=>'Ammunition','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Arrows','type'=>,'Ammunition','cost'=>,'1 gp','weight'=>,'1 lb','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Assassin&#39;s Blood (Ingested)','type'=>'Poison','cost'=>'150 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage');
$stock[] = new array ('name'=>'Assassin&#39;s Blood (Ingested)','type'=>,'Poison','cost'=>,'150 gp','weight'=>,'--','notes'=>,'Consumable, Damage');
$stock[] = new array ('name'=>'Backpack','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Backpack','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'5 lbs','notes'=>,'Container');
$stock[] = new array ('name'=>'Bagpipes','type'=>'Tool','cost'=>'30 gp','weight'=>'6 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Bagpipes','type'=>,'Tool','cost'=>,'30 gp','weight'=>,'6 lbs','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Ball Bearings (bag of 1,000)','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Control, Utility');
$stock[] = new array ('name'=>'Ball Bearings (bag of 1,000)','type'=>,'Adventuring Gear','cost'=>,'1 gp','weight'=>,'2 lbs','notes'=>,'Combat, Control, Utility');
$stock[] = new array ('name'=>'Barrel','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'70 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Barrel','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'70 lbs','notes'=>,'Container');
$stock[] = new array ('name'=>'Battleaxe','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'4 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Battleaxe','type'=>,'Martial Melee Weapon','cost'=>,'10 gp','weight'=>,'4 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Bedroll','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'7 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Bedroll','type'=>,'Adventuring Gear','cost'=>,'1 gp','weight'=>,'7 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Bell','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Communication, Utility');
$stock[] = new array ('name'=>'Bell','type'=>,'Adventuring Gear','cost'=>,'1 gp','weight'=>,'--','notes'=>,'Communication, Utility');
$stock[] = new array ('name'=>'Bit and Bridle','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Bit and Bridle','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'1 lb','notes'=>,'Utility');
$stock[] = new array ('name'=>'Block and Tackle','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Block and Tackle','type'=>,'Adventuring Gear','cost'=>,'1 gp','weight'=>,'5 lbs','notes'=>,'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Blowgun','type'=>'Martial Ranged Weapon','cost'=>'10 gp','weight'=>'1 lb','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Blowgun','type'=>,'Martial Ranged Weapon','cost'=>,'10 gp','weight'=>,'1 lb','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Blowgun Needles','type'=>'Ammunition','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Blowgun Needles','type'=>,'Ammunition','cost'=>,'1 gp','weight'=>,'1 lb','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Bomb','type'=>'Adventuring Gear','cost'=>'150 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Bomb','type'=>,'Adventuring Gear','cost'=>,'150 gp','weight'=>,'1 lb','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Book','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'5 lbs','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Book','type'=>,'Adventuring Gear','cost'=>,'25 gp','weight'=>,'5 lbs','notes'=>,'Social, Utility');
$stock[] = new array ('name'=>'Bottle, Glass','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'2 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Bottle, Glass','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'2 lbs','notes'=>,'Container');
$stock[] = new array ('name'=>'Breastplate','type'=>'Medium Armor','cost'=>'400 gp','weight'=>'20 lbs','description'=>'','notes'=>'AC 14');
$stock[] = new array ('name'=>'Breastplate','type'=>,'Medium Armor','cost'=>,'400 gp','weight'=>,'20 lbs','notes'=>,'AC 14');
$stock[] = new array ('name'=>'Warding','type'=>'Brewer&#39;s Supplies','cost'=>'Tool','weight'=>'20 gp','description'=>'','notes'=>'9 lbs');
$stock[] = new array ('name'=>'Warding','type'=>,'Brewer&#39;s Supplies','cost'=>,'Tool','weight'=>,'20 gp','notes'=>,'9 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Bullets, Renaissance','cost'=>'Ammunition','weight'=>'3 gp','description'=>'','notes'=>'2 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Bullets, Renaissance','cost'=>,'Ammunition','weight'=>,'3 gp','notes'=>,'2 lbs');
$stock[] = new array ('name'=>'Combat, Damage','type'=>'Burglar&#39;s Pack','cost'=>'Equipment Pack','weight'=>'16 gp','description'=>'','notes'=>'47 1/2 lbs');
$stock[] = new array ('name'=>'Combat, Damage','type'=>,'Burglar&#39;s Pack','cost'=>,'Equipment Pack','weight'=>,'16 gp','notes'=>,'47 1/2 lbs');
$stock[] = new array ('name'=>'Container, Exploration, Utility','type'=>'Burnt Othur Fumes (Inhaled)','cost'=>'Poison','weight'=>'500 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Container, Exploration, Utility','type'=>,'Burnt Othur Fumes (Inhaled)','cost'=>,'Poison','weight'=>,'500 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Consumable, Damage','type'=>'Calligrapher&#39;s Supplies','cost'=>'Tool','weight'=>'10 gp','description'=>'','notes'=>'5 lbs');
$stock[] = new array ('name'=>'Consumable, Damage','type'=>,'Calligrapher&#39;s Supplies','cost'=>,'Tool','weight'=>,'10 gp','notes'=>,'5 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Caltrops (bag of 20)','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'2 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Caltrops (bag of 20)','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'2 lbs');
$stock[] = new array ('name'=>'Combat, Damage, Movement','type'=>'Camel','cost'=>'Mount','weight'=>'50 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Combat, Damage, Movement','type'=>,'Camel','cost'=>,'Mount','weight'=>,'50 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Speed 50 ft., Carrying Capacity 480 lbs.','type'=>'Canoe','cost'=>'Adventuring Gear','weight'=>'50 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Speed 50 ft., Carrying Capacity 480 lbs.','type'=>,'Canoe','cost'=>,'Adventuring Gear','weight'=>,'50 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Utility','type'=>'Carpenter&#39;s Tools','cost'=>'Tool','weight'=>'8 gp','description'=>'','notes'=>'6 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Carpenter&#39;s Tools','cost'=>,'Tool','weight'=>,'8 gp','notes'=>,'6 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Carriage','cost'=>'Vehicle (Land)','weight'=>'100 gp','description'=>'','notes'=>'600 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Carriage','cost'=>,'Vehicle (Land)','weight'=>,'100 gp','notes'=>,'600 lbs');
$stock[] = new array ('name'=>'Exploration, Movement, Utility','type'=>'Cart','cost'=>'Vehicle (Land)','weight'=>'15 gp','description'=>'','notes'=>'200 lbs');
$stock[] = new array ('name'=>'Exploration, Movement, Utility','type'=>,'Cart','cost'=>,'Vehicle (Land)','weight'=>,'15 gp','notes'=>,'200 lbs');
$stock[] = new array ('name'=>'Exploration, Movement, Utility','type'=>'Cartographer&#39;s Tools','cost'=>'Tool','weight'=>'15 gp','description'=>'','notes'=>'6 lbs');
$stock[] = new array ('name'=>'Exploration, Movement, Utility','type'=>,'Cartographer&#39;s Tools','cost'=>,'Tool','weight'=>,'15 gp','notes'=>,'6 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Case, Crossbow Bolt','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'1 lb');
$stock[] = new array ('name'=>'Utility','type'=>,'Case, Crossbow Bolt','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'1 lb');
$stock[] = new array ('name'=>'Container','type'=>'Case, Map or Scroll','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'1 lb');
$stock[] = new array ('name'=>'Container','type'=>,'Case, Map or Scroll','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'1 lb');
$stock[] = new array ('name'=>'Container','type'=>'Chain (10 feet)','cost'=>'Adventuring Gear','weight'=>'5 gp','description'=>'','notes'=>'10 lbs');
$stock[] = new array ('name'=>'Container','type'=>,'Chain (10 feet)','cost'=>,'Adventuring Gear','weight'=>,'5 gp','notes'=>,'10 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Chain Mail','cost'=>'Heavy Armor','weight'=>'75 gp','description'=>'','notes'=>'55 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Chain Mail','cost'=>,'Heavy Armor','weight'=>,'75 gp','notes'=>,'55 lbs');
$stock[] = new array ('name'=>'AC 16','type'=>'Warding','cost'=>'Chain Shirt','weight'=>'Medium Armor','description'=>'','notes'=>'50 gp');
$stock[] = new array ('name'=>'AC 16','type'=>,'Warding','cost'=>,'Chain Shirt','weight'=>,'Medium Armor','notes'=>,'50 gp');
$stock[] = new array ('name'=>'20 lbs','type'=>'AC 13','cost'=>'Warding','weight'=>'Chariot','description'=>'','notes'=>'Vehicle (Land)');
$stock[] = new array ('name'=>'20 lbs','type'=>,'AC 13','cost'=>,'Warding','weight'=>,'Chariot','notes'=>,'Vehicle (Land)');
$stock[] = new array ('name'=>'250 gp','type'=>'100 lbs','cost'=>'Exploration, Movement, Utility','weight'=>'Chest','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'250 gp','type'=>,'100 lbs','cost'=>,'Exploration, Movement, Utility','weight'=>,'Chest','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>'25 lbs','cost'=>'Container','weight'=>'Climber&#39;s Kit','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>,'25 lbs','cost'=>,'Container','weight'=>,'Climber&#39;s Kit','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>'12 lbs','cost'=>'Exploration, Movement, Utility','weight'=>'Clothes, Costume','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>,'12 lbs','cost'=>,'Exploration, Movement, Utility','weight'=>,'Clothes, Costume','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>'4 lbs','cost'=>'Deception, Outerwear, Social','weight'=>'Clothes, Fine','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>,'4 lbs','cost'=>,'Deception, Outerwear, Social','weight'=>,'Clothes, Fine','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'15 gp','type'=>'6 lbs','cost'=>'Outerwear, Social','weight'=>'Clothes, Traveler&#39;s','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'15 gp','type'=>,'6 lbs','cost'=>,'Outerwear, Social','weight'=>,'Clothes, Traveler&#39;s','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'2 gp','type'=>'4 lbs','cost'=>'Outerwear, Social','weight'=>'Cobbler&#39;s Tools','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'2 gp','type'=>,'4 lbs','cost'=>,'Outerwear, Social','weight'=>,'Cobbler&#39;s Tools','notes'=>,'Tool');
$stock[] = new array ('name'=>'5 gp','type'=>'5 lbs','cost'=>'Utility','weight'=>'Component Pouch','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>,'5 lbs','cost'=>,'Utility','weight'=>,'Component Pouch','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>'2 lbs','cost'=>'Container, Utility','weight'=>'Cook&#39;s Utensils','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'25 gp','type'=>,'2 lbs','cost'=>,'Container, Utility','weight'=>,'Cook&#39;s Utensils','notes'=>,'Tool');
$stock[] = new array ('name'=>'1 gp','type'=>'8 lbs','cost'=>'Utility','weight'=>'Crawler Mucus (Contact)','description'=>'','notes'=>'Poison');
$stock[] = new array ('name'=>'1 gp','type'=>,'8 lbs','cost'=>,'Utility','weight'=>,'Crawler Mucus (Contact)','notes'=>,'Poison');
$stock[] = new array ('name'=>'200 gp','type'=>'--','cost'=>'Consumable, Damage, Debuff','weight'=>'Crossbow Bolts','description'=>'','notes'=>'Ammunition');
$stock[] = new array ('name'=>'200 gp','type'=>,'--','cost'=>,'Consumable, Damage, Debuff','weight'=>,'Crossbow Bolts','notes'=>,'Ammunition');
$stock[] = new array ('name'=>'1 gp','type'=>'1 1/2 lb','cost'=>'Combat, Damage','weight'=>'Crossbow, Hand','description'=>'','notes'=>'Martial Ranged Weapon');
$stock[] = new array ('name'=>'1 gp','type'=>,'1 1/2 lb','cost'=>,'Combat, Damage','weight'=>,'Crossbow, Hand','notes'=>,'Martial Ranged Weapon');
$stock[] = new array ('name'=>'75 gp','type'=>'3 lbs','cost'=>'Piercing','weight'=>'Combat, Damage','description'=>'','notes'=>'Crossbow, Heavy');
$stock[] = new array ('name'=>'75 gp','type'=>,'3 lbs','cost'=>,'Piercing','weight'=>,'Combat, Damage','notes'=>,'Crossbow, Heavy');
$stock[] = new array ('name'=>'Martial Ranged Weapon','type'=>'50 gp','cost'=>'18 lbs','weight'=>'Piercing','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Martial Ranged Weapon','type'=>,'50 gp','cost'=>,'18 lbs','weight'=>,'Piercing','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Crossbow, Light','type'=>'Simple Ranged Weapon','cost'=>'25 gp','weight'=>'5 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Crossbow, Light','type'=>,'Simple Ranged Weapon','cost'=>,'25 gp','weight'=>,'5 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Crowbar','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Crowbar','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'5 lbs','notes'=>,'Exploration, Utility');
$stock[] = new array ('name'=>'Crystal','type'=>'Arcane Focus','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Crystal','type'=>,'Arcane Focus','cost'=>,'10 gp','weight'=>,'1 lb','notes'=>,'Utility');
$stock[] = new array ('name'=>'Dagger','type'=>'Simple Melee Weapon','cost'=>'2 gp','weight'=>'1 lb','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Dagger','type'=>,'Simple Melee Weapon','cost'=>,'2 gp','weight'=>,'1 lb','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Diplomat&#39;s Pack','type'=>'Equipment Pack','cost'=>'39 gp','weight'=>'36 lbs','description'=>'','notes'=>'Container, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Diplomat&#39;s Pack','type'=>,'Equipment Pack','cost'=>,'39 gp','weight'=>,'36 lbs','notes'=>,'Container, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Disguise Kit','type'=>'Tool','cost'=>'25 gp','weight'=>'3 lbs','description'=>'','notes'=>'Deception, Utility');
$stock[] = new array ('name'=>'Disguise Kit','type'=>,'Tool','cost'=>,'25 gp','weight'=>,'3 lbs','notes'=>,'Deception, Utility');
$stock[] = new array ('name'=>'Donkey (or Mule)','type'=>'Mount','cost'=>'8 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 420 lbs.');
$stock[] = new array ('name'=>'Donkey (or Mule)','type'=>,'Mount','cost'=>,'8 gp','weight'=>,'--','notes'=>,'Speed 40 ft., Carrying Capacity 420 lbs.');
$stock[] = new array ('name'=>'Double-Bladed Scimitar','type'=>'Martial Melee Weapon','cost'=>'100 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Double-Bladed Scimitar','type'=>,'Martial Melee Weapon','cost'=>,'100 gp','weight'=>,'6 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Draft Horse','type'=>'Mount','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 540 lbs.');
$stock[] = new array ('name'=>'Draft Horse','type'=>,'Mount','cost'=>,'50 gp','weight'=>,'--','notes'=>,'Speed 40 ft., Carrying Capacity 540 lbs.');
$stock[] = new array ('name'=>'Dragonchess Set','type'=>'Tool','cost'=>'1 gp','weight'=>'1/2 lb','description'=>'','notes'=>'Social');
$stock[] = new array ('name'=>'Dragonchess Set','type'=>,'Tool','cost'=>,'1 gp','weight'=>,'1/2 lb','notes'=>,'Social');
$stock[] = new array ('name'=>'Drow Poison (Injury)','type'=>'Poison','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Drow Poison (Injury)','type'=>,'Poison','cost'=>,'200 gp','weight'=>,'--','notes'=>,'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Drum','type'=>'Tool','cost'=>'6 gp','weight'=>'3 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Drum','type'=>,'Tool','cost'=>,'6 gp','weight'=>,'3 lbs','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Dulcimer','type'=>'Tool','cost'=>'25 gp','weight'=>'10 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Dulcimer','type'=>,'Tool','cost'=>,'25 gp','weight'=>,'10 lbs','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Dungeoneer&#39;s Pack','type'=>'Equipment Pack','cost'=>'12 gp','weight'=>'61 1/2 lbs','description'=>'','notes'=>'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Dungeoneer&#39;s Pack','type'=>,'Equipment Pack','cost'=>,'12 gp','weight'=>,'61 1/2 lbs','notes'=>,'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Elephant','type'=>'Mount','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 1,320 lbs.');
$stock[] = new array ('name'=>'Elephant','type'=>,'Mount','cost'=>,'200 gp','weight'=>,'--','notes'=>,'Speed 40 ft., Carrying Capacity 1,320 lbs.');
$stock[] = new array ('name'=>'Emblem','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Emblem','type'=>,'Holy Symbol','cost'=>,'5 gp','weight'=>,'--','notes'=>,'Utility');
$stock[] = new array ('name'=>'Entertainer&#39;s Pack','type'=>'Equipment Pack','cost'=>'40 gp','weight'=>'38 lbs','description'=>'','notes'=>'Container, Deception, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Entertainer&#39;s Pack','type'=>,'Equipment Pack','cost'=>,'40 gp','weight'=>,'38 lbs','notes'=>,'Container, Deception, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Essence of Ether (Inhaled)','type'=>'Poison','cost'=>'300 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Essence of Ether (Inhaled)','type'=>,'Poison','cost'=>,'300 gp','weight'=>,'--','notes'=>,'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Explorer&#39;s Pack','type'=>'Equipment Pack','cost'=>'10 gp','weight'=>'59 lbs','description'=>'','notes'=>'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Explorer&#39;s Pack','type'=>,'Equipment Pack','cost'=>,'10 gp','weight'=>,'59 lbs','notes'=>,'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Fishing Tackle','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'4 lbs','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Fishing Tackle','type'=>,'Adventuring Gear','cost'=>,'1 gp','weight'=>,'4 lbs','notes'=>,'Social, Utility');
$stock[] = new array ('name'=>'Flail','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Flail','type'=>,'Martial Melee Weapon','cost'=>,'10 gp','weight'=>,'2 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Flute','type'=>'Tool','cost'=>'2 gp','weight'=>'1 lb','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Flute','type'=>,'Tool','cost'=>,'2 gp','weight'=>,'1 lb','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Forgery Kit','type'=>'Tool','cost'=>'15 gp','weight'=>'5 lbs','description'=>'','notes'=>'Deception, Utility');
$stock[] = new array ('name'=>'Forgery Kit','type'=>,'Tool','cost'=>,'15 gp','weight'=>,'5 lbs','notes'=>,'Deception, Utility');
$stock[] = new array ('name'=>'Galley','type'=>'Vehicle (Water)','cost'=>'30000 gp','weight'=>'--','description'=>'','notes'=>'Speed 4 mph');
$stock[] = new array ('name'=>'Galley','type'=>,'Vehicle (Water)','cost'=>,'30000 gp','weight'=>,'--','notes'=>,'Speed 4 mph');
$stock[] = new array ('name'=>'Glaive','type'=>'Martial Melee Weapon','cost'=>'20 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Glaive','type'=>,'Martial Melee Weapon','cost'=>,'20 gp','weight'=>,'6 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Glassblower&#39;s Tools','type'=>'Tool','cost'=>'30 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Glassblower&#39;s Tools','type'=>,'Tool','cost'=>,'30 gp','weight'=>,'5 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Grappling Hook','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'4 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Grappling Hook','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'4 lbs','notes'=>,'Exploration, Utility');
$stock[] = new array ('name'=>'Greataxe','type'=>'Martial Melee Weapon','cost'=>'30 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Greataxe','type'=>,'Martial Melee Weapon','cost'=>,'30 gp','weight'=>,'6 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Greatsword','type'=>'Martial Melee Weapon','cost'=>'50 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Greatsword','type'=>,'Martial Melee Weapon','cost'=>,'50 gp','weight'=>,'6 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Gunpowder, Keg','type'=>'Adventuring Gear','cost'=>'250 gp','weight'=>'20 lbs','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Gunpowder, Keg','type'=>,'Adventuring Gear','cost'=>,'250 gp','weight'=>,'20 lbs','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Gunpowder, Powder Horn','type'=>'Adventuring Gear','cost'=>'35 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Gunpowder, Powder Horn','type'=>,'Adventuring Gear','cost'=>,'35 gp','weight'=>,'2 lbs','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Halberd','type'=>'Martial Melee Weapon','cost'=>'20 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Halberd','type'=>,'Martial Melee Weapon','cost'=>,'20 gp','weight'=>,'6 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Half Plate','type'=>'Medium Armor','cost'=>'750 gp','weight'=>'40 lbs','description'=>'','notes'=>'AC 15');
$stock[] = new array ('name'=>'Half Plate','type'=>,'Medium Armor','cost'=>,'750 gp','weight'=>,'40 lbs','notes'=>,'AC 15');
$stock[] = new array ('name'=>'Warding','type'=>'Hammer','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'3 lbs');
$stock[] = new array ('name'=>'Warding','type'=>,'Hammer','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'3 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Hammer, Sledge','cost'=>'Adventuring Gear','weight'=>'2 gp','description'=>'','notes'=>'10 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Hammer, Sledge','cost'=>,'Adventuring Gear','weight'=>,'2 gp','notes'=>,'10 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Handaxe','cost'=>'Simple Melee Weapon','weight'=>'5 gp','description'=>'','notes'=>'2 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Handaxe','cost'=>,'Simple Melee Weapon','weight'=>,'5 gp','notes'=>,'2 lbs');
$stock[] = new array ('name'=>'Slashing','type'=>'Combat, Damage','cost'=>'Healer&#39;s Kit','weight'=>'Adventuring Gear','description'=>'','notes'=>'5 gp');
$stock[] = new array ('name'=>'Slashing','type'=>,'Combat, Damage','cost'=>,'Healer&#39;s Kit','weight'=>,'Adventuring Gear','notes'=>,'5 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>'Combat, Healing','cost'=>'Herbalism Kit','weight'=>'Tool','description'=>'','notes'=>'5 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>,'Combat, Healing','cost'=>,'Herbalism Kit','weight'=>,'Tool','notes'=>,'5 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>'Healing, Utility','cost'=>'Hide','weight'=>'Medium Armor','description'=>'','notes'=>'10 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>,'Healing, Utility','cost'=>,'Hide','weight'=>,'Medium Armor','notes'=>,'10 gp');
$stock[] = new array ('name'=>'12 lbs','type'=>'AC 12','cost'=>'Warding','weight'=>'Holy Water (flask)','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'12 lbs','type'=>,'AC 12','cost'=>,'Warding','weight'=>,'Holy Water (flask)','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>'1 lb','cost'=>'Combat, Damage, Utility','weight'=>'Horn','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'25 gp','type'=>,'1 lb','cost'=>,'Combat, Damage, Utility','weight'=>,'Horn','notes'=>,'Tool');
$stock[] = new array ('name'=>'3 gp','type'=>'2 lbs','cost'=>'Instrument','weight'=>'Hourglass','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'3 gp','type'=>,'2 lbs','cost'=>,'Instrument','weight'=>,'Hourglass','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>'1 lb','cost'=>'Utility','weight'=>'Hunting Trap','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'25 gp','type'=>,'1 lb','cost'=>,'Utility','weight'=>,'Hunting Trap','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>'25 lbs','cost'=>'Damage, Utility','weight'=>'Ink (1 ounce bottle)','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'5 gp','type'=>,'25 lbs','cost'=>,'Damage, Utility','weight'=>,'Ink (1 ounce bottle)','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'10 gp','type'=>'--','cost'=>'Communication, Consumable, Social, Utility','weight'=>'Insect Repellant-Salve','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'10 gp','type'=>,'--','cost'=>,'Communication, Consumable, Social, Utility','weight'=>,'Insect Repellant-Salve','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'1 gp','type'=>'--','cost'=>'Utility','weight'=>'Jeweler&#39;s Tools','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'1 gp','type'=>,'--','cost'=>,'Utility','weight'=>,'Jeweler&#39;s Tools','notes'=>,'Tool');
$stock[] = new array ('name'=>'25 gp','type'=>'2 lbs','cost'=>'Utility','weight'=>'Keelboat','description'=>'','notes'=>'Vehicle (Water)');
$stock[] = new array ('name'=>'25 gp','type'=>,'2 lbs','cost'=>,'Utility','weight'=>,'Keelboat','notes'=>,'Vehicle (Water)');
$stock[] = new array ('name'=>'3000 gp','type'=>'--','cost'=>'Speed 1 mph','weight'=>'Lance','description'=>'','notes'=>'Martial Melee Weapon');
$stock[] = new array ('name'=>'3000 gp','type'=>,'--','cost'=>,'Speed 1 mph','weight'=>,'Lance','notes'=>,'Martial Melee Weapon');
$stock[] = new array ('name'=>'10 gp','type'=>'6 lbs','cost'=>'Piercing','weight'=>'Combat, Control, Damage','description'=>'','notes'=>'Lantern, Bullseye');
$stock[] = new array ('name'=>'10 gp','type'=>,'6 lbs','cost'=>,'Piercing','weight'=>,'Combat, Control, Damage','notes'=>,'Lantern, Bullseye');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'10 gp','cost'=>'2 lbs','weight'=>'Exploration, Utility','description'=>'','notes'=>'Lantern, Hooded');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'10 gp','cost'=>,'2 lbs','weight'=>,'Exploration, Utility','notes'=>,'Lantern, Hooded');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'5 gp','cost'=>'2 lbs','weight'=>'Exploration, Utility','description'=>'','notes'=>'Leather');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'5 gp','cost'=>,'2 lbs','weight'=>,'Exploration, Utility','notes'=>,'Leather');
$stock[] = new array ('name'=>'Light Armor','type'=>'10 gp','cost'=>'10 lbs','weight'=>'AC 11','description'=>'','notes'=>'Warding');
$stock[] = new array ('name'=>'Light Armor','type'=>,'10 gp','cost'=>,'10 lbs','weight'=>,'AC 11','notes'=>,'Warding');
$stock[] = new array ('name'=>'Leatherworker&#39;s Tools','type'=>'Tool','cost'=>'5 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Leatherworker&#39;s Tools','type'=>,'Tool','cost'=>,'5 gp','weight'=>,'5 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Light Hammer','type'=>'Simple Melee Weapon','cost'=>'2 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Light Hammer','type'=>,'Simple Melee Weapon','cost'=>,'2 gp','weight'=>,'2 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Lock','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility, Warding');
$stock[] = new array ('name'=>'Lock','type'=>,'Adventuring Gear','cost'=>,'10 gp','weight'=>,'1 lb','notes'=>,'Utility, Warding');
$stock[] = new array ('name'=>'Longbow','type'=>'Martial Ranged Weapon','cost'=>'50 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Longbow','type'=>,'Martial Ranged Weapon','cost'=>,'50 gp','weight'=>,'2 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Longship','type'=>'Vehicle (Water)','cost'=>'10000 gp','weight'=>'--','description'=>'','notes'=>'Speed 3 mph');
$stock[] = new array ('name'=>'Longship','type'=>,'Vehicle (Water)','cost'=>,'10000 gp','weight'=>,'--','notes'=>,'Speed 3 mph');
$stock[] = new array ('name'=>'Longsword','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'3 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Longsword','type'=>,'Martial Melee Weapon','cost'=>,'15 gp','weight'=>,'3 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Lute','type'=>'Tool','cost'=>'35 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Lute','type'=>,'Tool','cost'=>,'35 gp','weight'=>,'2 lbs','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Lyre','type'=>'Tool','cost'=>'30 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Lyre','type'=>,'Tool','cost'=>,'30 gp','weight'=>,'2 lbs','notes'=>,'Instrument');
$stock[] = new array ('name'=>'Mace','type'=>'Simple Melee Weapon','cost'=>'5 gp','weight'=>'4 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Mace','type'=>,'Simple Melee Weapon','cost'=>,'5 gp','weight'=>,'4 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Magnifying Glass','type'=>'Adventuring Gear','cost'=>'100 gp','weight'=>'--','description'=>'','notes'=>'Detection, Exploration, Utility');
$stock[] = new array ('name'=>'Magnifying Glass','type'=>,'Adventuring Gear','cost'=>,'100 gp','weight'=>,'--','notes'=>,'Detection, Exploration, Utility');
$stock[] = new array ('name'=>'Malice (Inhaled)','type'=>'Poison','cost'=>'250 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Malice (Inhaled)','type'=>,'Poison','cost'=>,'250 gp','weight'=>,'--','notes'=>,'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Manacles','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'6 lbs','description'=>'','notes'=>'Control, Utility');
$stock[] = new array ('name'=>'Manacles','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'6 lbs','notes'=>,'Control, Utility');
$stock[] = new array ('name'=>'Mason&#39;s Tools','type'=>'Tool','cost'=>'10 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Mason&#39;s Tools','type'=>,'Tool','cost'=>,'10 gp','weight'=>,'8 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Mastiff','type'=>'Mount','cost'=>'25 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 195 lbs.');
$stock[] = new array ('name'=>'Mastiff','type'=>,'Mount','cost'=>,'25 gp','weight'=>,'--','notes'=>,'Speed 40 ft., Carrying Capacity 195 lbs.');
$stock[] = new array ('name'=>'Maul','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'10 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Maul','type'=>,'Martial Melee Weapon','cost'=>,'10 gp','weight'=>,'10 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Midnight Tears (Ingested)','type'=>'Poison','cost'=>'1500 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage');
$stock[] = new array ('name'=>'Midnight Tears (Ingested)','type'=>,'Poison','cost'=>,'1500 gp','weight'=>,'--','notes'=>,'Consumable, Damage');
$stock[] = new array ('name'=>'Mirror, Steel','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'1/2 lb','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Mirror, Steel','type'=>,'Adventuring Gear','cost'=>,'5 gp','weight'=>,'1/2 lb','notes'=>,'Social, Utility');
$stock[] = new array ('name'=>'Monster Hunter&#39;s Pack','type'=>'Equipment Pack','cost'=>'33 gp','weight'=>'49 lbs','description'=>'','notes'=>'Container, Control, Utility');
$stock[] = new array ('name'=>'Monster Hunter&#39;s Pack','type'=>,'Equipment Pack','cost'=>,'33 gp','weight'=>,'49 lbs','notes'=>,'Container, Control, Utility');
$stock[] = new array ('name'=>'Morningstar','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'4 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Morningstar','type'=>,'Martial Melee Weapon','cost'=>,'15 gp','weight'=>,'4 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Musket','type'=>'Firearms Ranged Weapon','cost'=>'500 gp','weight'=>'10 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Musket','type'=>,'Firearms Ranged Weapon','cost'=>,'500 gp','weight'=>,'10 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Navigator&#39;s Tools','type'=>'Tool','cost'=>'25 gp','weight'=>'2 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Navigator&#39;s Tools','type'=>,'Tool','cost'=>,'25 gp','weight'=>,'2 lbs','notes'=>,'Exploration, Utility');
$stock[] = new array ('name'=>'Net','type'=>'Martial Ranged Weapon','cost'=>'1 gp','weight'=>'3 lbs','description'=>'Bludgeoning','notes'=>'Combat, Control');
$stock[] = new array ('name'=>'Net','type'=>,'Martial Ranged Weapon','cost'=>,'1 gp','weight'=>,'3 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Oil of Taggit (Contact)','type'=>'Poison','cost'=>'400 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Oil of Taggit (Contact)','type'=>,'Poison','cost'=>,'400 gp','weight'=>,'--','notes'=>,'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Orb','type'=>'Arcane Focus','cost'=>'20 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Orb','type'=>,'Arcane Focus','cost'=>,'20 gp','weight'=>,'3 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Padded','type'=>'Light Armor','cost'=>'5 gp','weight'=>'8 lbs','description'=>'','notes'=>'AC 11');
$stock[] = new array ('name'=>'Padded','type'=>,'Light Armor','cost'=>,'5 gp','weight'=>,'8 lbs','notes'=>,'AC 11');
$stock[] = new array ('name'=>'Warding','type'=>'Painter&#39;s Supplies','cost'=>'Tool','weight'=>'10 gp','description'=>'','notes'=>'5 lbs');
$stock[] = new array ('name'=>'Warding','type'=>,'Painter&#39;s Supplies','cost'=>,'Tool','weight'=>,'10 gp','notes'=>,'5 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Pale Tincture (Ingested)','cost'=>'Poison','weight'=>'250 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Utility','type'=>,'Pale Tincture (Ingested)','cost'=>,'Poison','weight'=>,'250 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Consumable, Damage, Debuff','type'=>'Pan Flute','cost'=>'Tool','weight'=>'12 gp','description'=>'','notes'=>'2 lbs');
$stock[] = new array ('name'=>'Consumable, Damage, Debuff','type'=>,'Pan Flute','cost'=>,'Tool','weight'=>,'12 gp','notes'=>,'2 lbs');
$stock[] = new array ('name'=>'Instrument','type'=>'Perfume (vial)','cost'=>'Adventuring Gear','weight'=>'5 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Instrument','type'=>,'Perfume (vial)','cost'=>,'Adventuring Gear','weight'=>,'5 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Consumable, Social, Utility','type'=>'Pick, Miner&#39;s','cost'=>'Adventuring Gear','weight'=>'2 gp','description'=>'','notes'=>'10 lbs');
$stock[] = new array ('name'=>'Consumable, Social, Utility','type'=>,'Pick, Miner&#39;s','cost'=>,'Adventuring Gear','weight'=>,'2 gp','notes'=>,'10 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Pike','cost'=>'Martial Melee Weapon','weight'=>'5 gp','description'=>'','notes'=>'18 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Pike','cost'=>,'Martial Melee Weapon','weight'=>,'5 gp','notes'=>,'18 lbs');
$stock[] = new array ('name'=>'Piercing','type'=>'Combat, Control, Damage','cost'=>'Pistol','weight'=>'Firearms Ranged Weapon','description'=>'','notes'=>'250 gp');
$stock[] = new array ('name'=>'Piercing','type'=>,'Combat, Control, Damage','cost'=>,'Pistol','weight'=>,'Firearms Ranged Weapon','notes'=>,'250 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>'Piercing','cost'=>'Combat, Damage','weight'=>'Plate','description'=>'','notes'=>'Heavy Armor');
$stock[] = new array ('name'=>'3 lbs','type'=>,'Piercing','cost'=>,'Combat, Damage','weight'=>,'Plate','notes'=>,'Heavy Armor');
$stock[] = new array ('name'=>'1500 gp','type'=>'65 lbs','cost'=>'AC 18','weight'=>'Warding','description'=>'','notes'=>'Poison, Basic (vial)');
$stock[] = new array ('name'=>'1500 gp','type'=>,'65 lbs','cost'=>,'AC 18','weight'=>,'Warding','notes'=>,'Poison, Basic (vial)');
$stock[] = new array ('name'=>'Poison','type'=>'100 gp','cost'=>'--','weight'=>'Combat, Consumable, Damage, Utility','description'=>'','notes'=>'Poisoner&#39;s Kit');
$stock[] = new array ('name'=>'Poison','type'=>,'100 gp','cost'=>,'--','weight'=>,'Combat, Consumable, Damage, Utility','notes'=>,'Poisoner&#39;s Kit');
$stock[] = new array ('name'=>'Tool','type'=>'50 gp','cost'=>'2 lbs','weight'=>'Utility','description'=>'','notes'=>'Pony');
$stock[] = new array ('name'=>'Tool','type'=>,'50 gp','cost'=>,'2 lbs','weight'=>,'Utility','notes'=>,'Pony');
$stock[] = new array ('name'=>'Mount','type'=>'30 gp','cost'=>'--','weight'=>'Speed 40 ft., Carrying Capacity 225 lbs.','description'=>'','notes'=>'Pot, Iron');
$stock[] = new array ('name'=>'Mount','type'=>,'30 gp','cost'=>,'--','weight'=>,'Speed 40 ft., Carrying Capacity 225 lbs.','notes'=>,'Pot, Iron');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'2 gp','cost'=>'10 lbs','weight'=>'Container','description'=>'','notes'=>'Potion of Healing');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'2 gp','cost'=>,'10 lbs','weight'=>,'Container','notes'=>,'Potion of Healing');
$stock[] = new array ('name'=>'Potion','type'=>'50 gp','cost'=>'1/2 lb','weight'=>'Combat, Consumable, Healing','description'=>'','notes'=>'Potter&#39;s Tools');
$stock[] = new array ('name'=>'Potion','type'=>,'50 gp','cost'=>,'1/2 lb','weight'=>,'Combat, Consumable, Healing','notes'=>,'Potter&#39;s Tools');
$stock[] = new array ('name'=>'Tool','type'=>'10 gp','cost'=>'3 lbs','weight'=>'Utility','description'=>'','notes'=>'Priest&#39;s Pack');
$stock[] = new array ('name'=>'Tool','type'=>,'10 gp','cost'=>,'3 lbs','weight'=>,'Utility','notes'=>,'Priest&#39;s Pack');
$stock[] = new array ('name'=>'Equipment Pack','type'=>'19 gp','cost'=>'24 lbs','weight'=>'Container, Exploration, Outerwear, Social, Utility','description'=>'','notes'=>'Purple Worm Poison (Injury)');
$stock[] = new array ('name'=>'Equipment Pack','type'=>,'19 gp','cost'=>,'24 lbs','weight'=>,'Container, Exploration, Outerwear, Social, Utility','notes'=>,'Purple Worm Poison (Injury)');
$stock[] = new array ('name'=>'Poison','type'=>'2000 gp','cost'=>'--','weight'=>'Consumable, Damage, Debuff','description'=>'','notes'=>'Quiver');
$stock[] = new array ('name'=>'Poison','type'=>,'2000 gp','cost'=>,'--','weight'=>,'Consumable, Damage, Debuff','notes'=>,'Quiver');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'1 gp','cost'=>'1 lb','weight'=>'Container','description'=>'','notes'=>'Rain Catcher');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'1 gp','cost'=>,'1 lb','weight'=>,'Container','notes'=>,'Rain Catcher');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'1 gp','cost'=>'5 lbs','weight'=>'Utility','description'=>'','notes'=>'Ram, Portable');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'1 gp','cost'=>,'5 lbs','weight'=>,'Utility','notes'=>,'Ram, Portable');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'4 gp','cost'=>'35 lbs','weight'=>'Exploration, Utility','description'=>'','notes'=>'Rapier');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'4 gp','cost'=>,'35 lbs','weight'=>,'Exploration, Utility','notes'=>,'Rapier');
$stock[] = new array ('name'=>'Martial Melee Weapon','type'=>'25 gp','cost'=>'2 lbs','weight'=>'Piercing','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Martial Melee Weapon','type'=>,'25 gp','cost'=>,'2 lbs','weight'=>,'Piercing','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Reliquary','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Reliquary','type'=>,'Holy Symbol','cost'=>,'5 gp','weight'=>,'2 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Riding Horse','type'=>'Mount','cost'=>'75 gp','weight'=>'--','description'=>'','notes'=>'Speed 60 ft., Carrying Capacity 480 lbs.');
$stock[] = new array ('name'=>'Riding Horse','type'=>,'Mount','cost'=>,'75 gp','weight'=>,'--','notes'=>,'Speed 60 ft., Carrying Capacity 480 lbs.');
$stock[] = new array ('name'=>'Ring Mail','type'=>'Heavy Armor','cost'=>'30 gp','weight'=>'40 lbs','description'=>'','notes'=>'AC 14');
$stock[] = new array ('name'=>'Ring Mail','type'=>,'Heavy Armor','cost'=>,'30 gp','weight'=>,'40 lbs','notes'=>,'AC 14');
$stock[] = new array ('name'=>'Warding','type'=>'Robes','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'4 lbs');
$stock[] = new array ('name'=>'Warding','type'=>,'Robes','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'4 lbs');
$stock[] = new array ('name'=>'Outerwear, Utility','type'=>'Rod','cost'=>'Arcane Focus','weight'=>'10 gp','description'=>'','notes'=>'2 lbs');
$stock[] = new array ('name'=>'Outerwear, Utility','type'=>,'Rod','cost'=>,'Arcane Focus','weight'=>,'10 gp','notes'=>,'2 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Rope, Hempen (50 feet)','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'10 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Rope, Hempen (50 feet)','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'10 lbs');
$stock[] = new array ('name'=>'Exploration, Utility','type'=>'Rope, Silk (50 feet)','cost'=>'Adventuring Gear','weight'=>'10 gp','description'=>'','notes'=>'5 lbs');
$stock[] = new array ('name'=>'Exploration, Utility','type'=>,'Rope, Silk (50 feet)','cost'=>,'Adventuring Gear','weight'=>,'10 gp','notes'=>,'5 lbs');
$stock[] = new array ('name'=>'Exploration, Utility','type'=>'Rowboat','cost'=>'Vehicle (Water)','weight'=>'50 gp','description'=>'','notes'=>'100 lbs');
$stock[] = new array ('name'=>'Exploration, Utility','type'=>,'Rowboat','cost'=>,'Vehicle (Water)','weight'=>,'50 gp','notes'=>,'100 lbs');
$stock[] = new array ('name'=>'Speed 1 1/2 mph','type'=>'Saddle, Exotic','cost'=>'Adventuring Gear','weight'=>'60 gp','description'=>'','notes'=>'40 lbs');
$stock[] = new array ('name'=>'Speed 1 1/2 mph','type'=>,'Saddle, Exotic','cost'=>,'Adventuring Gear','weight'=>,'60 gp','notes'=>,'40 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Saddle, Military','cost'=>'Adventuring Gear','weight'=>'20 gp','description'=>'','notes'=>'30 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Saddle, Military','cost'=>,'Adventuring Gear','weight'=>,'20 gp','notes'=>,'30 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Saddle, Pack','cost'=>'Adventuring Gear','weight'=>'5 gp','description'=>'','notes'=>'15 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Saddle, Pack','cost'=>,'Adventuring Gear','weight'=>,'5 gp','notes'=>,'15 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Saddle, Riding','cost'=>'Adventuring Gear','weight'=>'10 gp','description'=>'','notes'=>'25 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Saddle, Riding','cost'=>,'Adventuring Gear','weight'=>,'10 gp','notes'=>,'25 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Saddlebags','cost'=>'Adventuring Gear','weight'=>'4 gp','description'=>'','notes'=>'8 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Saddlebags','cost'=>,'Adventuring Gear','weight'=>,'4 gp','notes'=>,'8 lbs');
$stock[] = new array ('name'=>'Container, Utility','type'=>'Sailing Ship','cost'=>'Vehicle (Water)','weight'=>'10000 gp','description'=>'','notes'=>'--');
$stock[] = new array ('name'=>'Container, Utility','type'=>,'Sailing Ship','cost'=>,'Vehicle (Water)','weight'=>,'10000 gp','notes'=>,'--');
$stock[] = new array ('name'=>'Speed 2 mph','type'=>'Scale Mail','cost'=>'Medium Armor','weight'=>'50 gp','description'=>'','notes'=>'45 lbs');
$stock[] = new array ('name'=>'Speed 2 mph','type'=>,'Scale Mail','cost'=>,'Medium Armor','weight'=>,'50 gp','notes'=>,'45 lbs');
$stock[] = new array ('name'=>'AC 14','type'=>'Warding','cost'=>'Scale, Merchant&#39;s','weight'=>'Adventuring Gear','description'=>'','notes'=>'5 gp');
$stock[] = new array ('name'=>'AC 14','type'=>,'Warding','cost'=>,'Scale, Merchant&#39;s','weight'=>,'Adventuring Gear','notes'=>,'5 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>'Social, Utility','cost'=>'Scholar&#39;s Pack','weight'=>'Equipment Pack','description'=>'','notes'=>'40 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>,'Social, Utility','cost'=>,'Scholar&#39;s Pack','weight'=>,'Equipment Pack','notes'=>,'40 gp');
$stock[] = new array ('name'=>'10 lbs','type'=>'Container, Social, Utility','cost'=>'Scimitar','weight'=>'Martial Melee Weapon','description'=>'','notes'=>'25 gp');
$stock[] = new array ('name'=>'10 lbs','type'=>,'Container, Social, Utility','cost'=>,'Scimitar','weight'=>,'Martial Melee Weapon','notes'=>,'25 gp');
$stock[] = new array ('name'=>'3 lbs','type'=>'Slashing','cost'=>'Combat, Damage','weight'=>'Serpent Venom (Injury)','description'=>'','notes'=>'Poison');
$stock[] = new array ('name'=>'3 lbs','type'=>,'Slashing','cost'=>,'Combat, Damage','weight'=>,'Serpent Venom (Injury)','notes'=>,'Poison');
$stock[] = new array ('name'=>'200 gp','type'=>'--','cost'=>'Consumable, Damage, Debuff','weight'=>'Shawm','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'200 gp','type'=>,'--','cost'=>,'Consumable, Damage, Debuff','weight'=>,'Shawm','notes'=>,'Tool');
$stock[] = new array ('name'=>'2 gp','type'=>'1 lb','cost'=>'Instrument','weight'=>'Shield','description'=>'','notes'=>'Shield');
$stock[] = new array ('name'=>'2 gp','type'=>,'1 lb','cost'=>,'Instrument','weight'=>,'Shield','notes'=>,'Shield');
$stock[] = new array ('name'=>'10 gp','type'=>'6 lbs','cost'=>'AC 2','weight'=>'Warding','description'=>'','notes'=>'Shortbow');
$stock[] = new array ('name'=>'10 gp','type'=>,'6 lbs','cost'=>,'AC 2','weight'=>,'Warding','notes'=>,'Shortbow');
$stock[] = new array ('name'=>'Simple Ranged Weapon','type'=>'25 gp','cost'=>'2 lbs','weight'=>'Piercing','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Simple Ranged Weapon','type'=>,'25 gp','cost'=>,'2 lbs','weight'=>,'Piercing','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Shortsword','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Shortsword','type'=>,'Martial Melee Weapon','cost'=>,'10 gp','weight'=>,'2 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Shovel','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Shovel','type'=>,'Adventuring Gear','cost'=>,'2 gp','weight'=>,'5 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Sickle','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'2 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Sickle','type'=>,'Simple Melee Weapon','cost'=>,'1 gp','weight'=>,'2 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Signet Ring','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'--','description'=>'','notes'=>'Communication, Social, Utility');
$stock[] = new array ('name'=>'Signet Ring','type'=>,'Adventuring Gear','cost'=>,'5 gp','weight'=>,'--','notes'=>,'Communication, Social, Utility');
$stock[] = new array ('name'=>'Sled','type'=>'Vehicle (Land)','cost'=>'20 gp','weight'=>'300 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Sled','type'=>,'Vehicle (Land)','cost'=>,'20 gp','weight'=>,'300 lbs','notes'=>,'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Smith&#39;s Tools','type'=>'Tool','cost'=>'20 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Smith&#39;s Tools','type'=>,'Tool','cost'=>,'20 gp','weight'=>,'8 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Spear','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'3 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Spear','type'=>,'Simple Melee Weapon','cost'=>,'1 gp','weight'=>,'3 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'Spellbook','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Spellbook','type'=>,'Adventuring Gear','cost'=>,'50 gp','weight'=>,'3 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Spiked Armor','type'=>'Medium Armor','cost'=>'75 gp','weight'=>'45 lbs','description'=>'','notes'=>'AC 14');
$stock[] = new array ('name'=>'Spiked Armor','type'=>,'Medium Armor','cost'=>,'75 gp','weight'=>,'45 lbs','notes'=>,'AC 14');
$stock[] = new array ('name'=>'Damage, Warding','type'=>'Spikes, Iron (10)','cost'=>'Adventuring Gear','weight'=>'1 gp','description'=>'','notes'=>'5 lbs');
$stock[] = new array ('name'=>'Damage, Warding','type'=>,'Spikes, Iron (10)','cost'=>,'Adventuring Gear','weight'=>,'1 gp','notes'=>,'5 lbs');
$stock[] = new array ('name'=>'Utility','type'=>'Splint','cost'=>'Heavy Armor','weight'=>'200 gp','description'=>'','notes'=>'60 lbs');
$stock[] = new array ('name'=>'Utility','type'=>,'Splint','cost'=>,'Heavy Armor','weight'=>,'200 gp','notes'=>,'60 lbs');
$stock[] = new array ('name'=>'AC 17','type'=>'Warding','cost'=>'Sprig of Mistletoe','weight'=>'Druidic Focus','description'=>'','notes'=>'1 gp');
$stock[] = new array ('name'=>'AC 17','type'=>,'Warding','cost'=>,'Sprig of Mistletoe','weight'=>,'Druidic Focus','notes'=>,'1 gp');
$stock[] = new array ('name'=>'--','type'=>'Utility','cost'=>'Spyglass','weight'=>'Adventuring Gear','description'=>'','notes'=>'1000 gp');
$stock[] = new array ('name'=>'--','type'=>,'Utility','cost'=>,'Spyglass','weight'=>,'Adventuring Gear','notes'=>,'1000 gp');
$stock[] = new array ('name'=>'1 lb','type'=>'Exploration, Social, Utility','cost'=>'Staff','weight'=>'Arcane Focus','description'=>'','notes'=>'5 gp');
$stock[] = new array ('name'=>'1 lb','type'=>,'Exploration, Social, Utility','cost'=>,'Staff','weight'=>,'Arcane Focus','notes'=>,'5 gp');
$stock[] = new array ('name'=>'4 lbs','type'=>'Utility','cost'=>'Studded Leather','weight'=>'Light Armor','description'=>'','notes'=>'45 gp');
$stock[] = new array ('name'=>'4 lbs','type'=>,'Utility','cost'=>,'Studded Leather','weight'=>,'Light Armor','notes'=>,'45 gp');
$stock[] = new array ('name'=>'13 lbs','type'=>'AC 12','cost'=>'Warding','weight'=>'Tent, Two-Person','description'=>'','notes'=>'Adventuring Gear');
$stock[] = new array ('name'=>'13 lbs','type'=>,'AC 12','cost'=>,'Warding','weight'=>,'Tent, Two-Person','notes'=>,'Adventuring Gear');
$stock[] = new array ('name'=>'2 gp','type'=>'20 lbs','cost'=>'Exploration, Social, Utility','weight'=>'Thieves&#39; Tools','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'2 gp','type'=>,'20 lbs','cost'=>,'Exploration, Social, Utility','weight'=>,'Thieves&#39; Tools','notes'=>,'Tool');
$stock[] = new array ('name'=>'25 gp','type'=>'1 lb','cost'=>'Exploration, Utility','weight'=>'Three-Dragon Ante Set','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'25 gp','type'=>,'1 lb','cost'=>,'Exploration, Utility','weight'=>,'Three-Dragon Ante Set','notes'=>,'Tool');
$stock[] = new array ('name'=>'1 gp','type'=>'--','cost'=>'Social','weight'=>'Tinker&#39;s Tools','description'=>'','notes'=>'Tool');
$stock[] = new array ('name'=>'1 gp','type'=>,'--','cost'=>,'Social','weight'=>,'Tinker&#39;s Tools','notes'=>,'Tool');
$stock[] = new array ('name'=>'50 gp','type'=>'10 lbs','cost'=>'Utility','weight'=>'Torpor (Ingested)','description'=>'','notes'=>'Poison');
$stock[] = new array ('name'=>'50 gp','type'=>,'10 lbs','cost'=>,'Utility','weight'=>,'Torpor (Ingested)','notes'=>,'Poison');
$stock[] = new array ('name'=>'600 gp','type'=>'--','cost'=>'Consumable, Damage, Debuff','weight'=>'Totem','description'=>'','notes'=>'Druidic Focus');
$stock[] = new array ('name'=>'600 gp','type'=>,'--','cost'=>,'Consumable, Damage, Debuff','weight'=>,'Totem','notes'=>,'Druidic Focus');
$stock[] = new array ('name'=>'1 gp','type'=>'--','cost'=>'Utility','weight'=>'Trident','description'=>'','notes'=>'Martial Melee Weapon');
$stock[] = new array ('name'=>'1 gp','type'=>,'--','cost'=>,'Utility','weight'=>,'Trident','notes'=>,'Martial Melee Weapon');
$stock[] = new array ('name'=>'5 gp','type'=>'4 lbs','cost'=>'Piercing','weight'=>'Combat, Damage','description'=>'','notes'=>'Truth Serum (Ingested)');
$stock[] = new array ('name'=>'5 gp','type'=>,'4 lbs','cost'=>,'Piercing','weight'=>,'Combat, Damage','notes'=>,'Truth Serum (Ingested)');
$stock[] = new array ('name'=>'Poison','type'=>'150 gp','cost'=>'--','weight'=>'Consumable, Debuff, Utility','description'=>'','notes'=>'Vial');
$stock[] = new array ('name'=>'Poison','type'=>,'150 gp','cost'=>,'--','weight'=>,'Consumable, Debuff, Utility','notes'=>,'Vial');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>'1 gp','cost'=>'--','weight'=>'Container','description'=>'','notes'=>'Viol');
$stock[] = new array ('name'=>'Adventuring Gear','type'=>,'1 gp','cost'=>,'--','weight'=>,'Container','notes'=>,'Viol');
$stock[] = new array ('name'=>'Tool','type'=>'30 gp','cost'=>'1 lb','weight'=>'Instrument','description'=>'','notes'=>'Wagon');
$stock[] = new array ('name'=>'Tool','type'=>,'30 gp','cost'=>,'1 lb','weight'=>,'Instrument','notes'=>,'Wagon');
$stock[] = new array ('name'=>'Vehicle (Land)','type'=>'35 gp','cost'=>'400 lbs','weight'=>'Exploration, Movement, Utility','description'=>'','notes'=>'Wand');
$stock[] = new array ('name'=>'Vehicle (Land)','type'=>,'35 gp','cost'=>,'400 lbs','weight'=>,'Exploration, Movement, Utility','notes'=>,'Wand');
$stock[] = new array ('name'=>'Arcane Focus','type'=>'10 gp','cost'=>'1 lb','weight'=>'Utility','description'=>'','notes'=>'War Pick');
$stock[] = new array ('name'=>'Arcane Focus','type'=>,'10 gp','cost'=>,'1 lb','weight'=>,'Utility','notes'=>,'War Pick');
$stock[] = new array ('name'=>'Martial Melee Weapon','type'=>'5 gp','cost'=>'2 lbs','weight'=>'Piercing','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Martial Melee Weapon','type'=>,'5 gp','cost'=>,'2 lbs','weight'=>,'Piercing','notes'=>,'Combat, Damage');
$stock[] = new array ('name'=>'Warhammer','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Warhammer','type'=>,'Martial Melee Weapon','cost'=>,'15 gp','weight'=>,'2 lbs','notes'=>,'Bludgeoning');
$stock[] = new array ('name'=>'Warhorse','type'=>'Mount','cost'=>'400 gp','weight'=>'--','description'=>'','notes'=>'Speed 60 ft., Carry Capacity 540 lbs.');
$stock[] = new array ('name'=>'Warhorse','type'=>,'Mount','cost'=>,'400 gp','weight'=>,'--','notes'=>,'Speed 60 ft., Carry Capacity 540 lbs.');
$stock[] = new array ('name'=>'Warship','type'=>'Vehicle (Water)','cost'=>'25000 gp','weight'=>'--','description'=>'','notes'=>'2 1/2 mph');
$stock[] = new array ('name'=>'Warship','type'=>,'Vehicle (Water)','cost'=>,'25000 gp','weight'=>,'--','notes'=>,'2 1/2 mph');
$stock[] = new array ('name'=>'Weaver&#39;s Tools','type'=>'Tool','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Weaver&#39;s Tools','type'=>,'Tool','cost'=>,'1 gp','weight'=>,'5 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Whip','type'=>'Martial Melee Weapon','cost'=>'2 gp','weight'=>'3 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Whip','type'=>,'Martial Melee Weapon','cost'=>,'2 gp','weight'=>,'3 lbs','notes'=>,'Slashing');
$stock[] = new array ('name'=>'Woodcarver&#39;s Tools','type'=>'Tool','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Woodcarver&#39;s Tools','type'=>,'Tool','cost'=>,'1 gp','weight'=>,'5 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Wooden Staff','type'=>'Druidic Focus','cost'=>'5 gp','weight'=>'4 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Wooden Staff','type'=>,'Druidic Focus','cost'=>,'5 gp','weight'=>,'4 lbs','notes'=>,'Utility');
$stock[] = new array ('name'=>'Wyvern Poison (Injury)','type'=>'Poison','cost'=>'1200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Wyvern Poison (Injury)','type'=>,'Poison','cost'=>,'1200 gp','weight'=>,'--','notes'=>,'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Yew Wand','type'=>'Druidic Focus','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Yew Wand','type'=>,'Druidic Focus','cost'=>,'10 gp','weight'=>,'1 lb','notes'=>,'Utility');
$stock[] = new array ('name'=>'Yklwa','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Yklwa','type'=>,'Simple Melee Weapon','cost'=>,'1 gp','weight'=>,'2 lbs','notes'=>,'Piercing');
$stock[] = new array ('name'=>'','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'','type'=>,'Simple Melee Weapon','cost'=>,'1 gp','weight'=>,'2 lbs','notes'=>,'Piercing');
